name: siddhan_logs_employee
description: Siddhan Employee Logs - Employee mobile app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Dependency Injection
  get_it: ^8.0.3

  # Networking
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  web_socket_channel: ^3.0.1

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.3

  # Location & Geofence
  geolocator: ^13.0.1

  # UI
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  # Utilities
  intl: ^0.20.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  http_parser: ^4.0.0
  google_mlkit_face_detection: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
